### ISSUE TITLE
Guide URL is down

### ISSUE THREAD

**Issue by mikefaille** [leitec/openwrt-leitec#5]
Some help to build this ? ty
https://jakko.me/setting-up-openwrt-on-a-wrt110-and-other-ralink-based-routers/

**Comment by leitec** [comment]
The official documentation is available:

http://wiki.openwrt.org/doc/howto/build

Apart from installing the prerequisite packages, all you should have to do is run `make menuconfig` and select `Ralink RT288x/RT3xxx` as the target and `RT288x based boards` as the subtarget. Then, `make` will build the image for all supported routers. You can use `make -j<whatever>` to speed up your build on multicore machines.

I'll put this up in a wiki page and take down the link to jakko's page.

**Comment by mikefaille** [comment]
Thank you. It work for me. 
For my case, I will upgrade my wrt160nV2. For the 1rst install from OEM image, I must rename ```image-wrt160nv2.uImage``` to ```image-wrt160nv2.uImage.bin``` because OEM``` web UI only accept ```.bin``` extenssion.

**Comment by leitec** [comment]
No, that is not the image. That is only the kernel image. You will brick your router if you flash that.

You want to flash bin/ramips/openwrt-ramips-rt288x-wrt160nv2-squashfs-factory-code.bin instead.

**Comment by mikefaille** [comment]
Hum, @leitec  image-wrt160nv2.uImage.bin just work. I have done few reboots and it keep my config like I want.

**Comment by leitec** [comment]
Well, in this case you were lucky that the image happens to contain the whole filesystem due to the weird format the factory firmware wants to flash. In any other model supported here you would have bricked your router because you would have flashed only the kernel. I'm surprised it worked, in any case, because there's still one more step between that and the image in `bin/ramips`.

Anyone else reading this in the future, the images are in the `bin/ramips` directory. Don't go poking around in `build_dir` unless you know what you are doing and can recover the router using u-Boot and the serial console.

**Comment by mikefaille** [comment]
Trust me. I know what vmlinuz mean.
@leitec You 'll be sure that I'll use ```bin/ramip``` in future. Thank you !

**Comment by leitec** [comment]
Great, I'm glad it's working for you.
