### ISSUE TITLE
New Linksys WRT160N V2 user with questions. 

### ISSUE THREAD

**Issue by ShapeShifter499** [leitec/openwrt-leitec#7]
Hi,

Not so much a issue but just questions, how often do you update the prebuilt images over at http://staticky.com/dl/openwrt-leitec/12.09.1/ramips/rt288x/   ??    Also do you have a list of what packages are included?   I got a Linksys WRT160N V2 from a thrift shop hopping I could stick open source software on it after my success with getting Netgear WNR1000 v2 and a Linksys WRT54G both from a thrift shop working with openwrt. I'm going to load the openwrt-ramips-rt288x-wrt160nv2-squashfs-factory-code.bin file you made right after this using the stock gui upgrade option.  One last question, any hope on getting this router up to the latest stable Barrier Breaker 14.07?

Thank you in advance, Lance

**Comment by ShapeShifter499** [comment]
Oh I forgot to ask, do you think zram would help the low ram issue on the WRT160N V2?

**Comment by leitec** [comment]
I update the binary image whenever I commit something new, mostly the occasional package update. It's the base package set plus ddns-scripts, ipv6-support (meta package, so everything that includes), relayd, iwinfo, openvpn, dropbearconvert, iperf3 and uboot-envtools. I think that's all of them. The binary images include just the base package set, so anything else must be installed with opkg.

It's possible to add support in Barrier Breaker and above, but when I tried this the router ran out of memory right away when trying to enable wifi.

zram does help, but it's not a miracle. If you build openwrt-leitec you can build with zram. However, since it's kernel 3.3 it is a fairly early version of the module and not necessarily stable. I have not tried zram with BB or newer.

**Comment by ShapeShifter499** [comment]
Would you be willing to test a build of Barrier Breaker with zram enabled? I would test it myself but I don't know how to compile the latest Barrier Breaker with modifications for the WRT160N V2

**Comment by ShapeShifter499** [comment]
I was discussing the low ram in #openwrt in Freenode IRC channel and someone mentioned this https://dev.openwrt.org/changeset/40981   might help with low ram in Barrier Breaker.

**Comment by leitec** [comment]
I already backported the three commits around 40981 (create low_mem tag, reduce squashfs block size to 64k, remove some unnecessary ipv6 modules by default). It helped a bit to make it not run out of memory, but it wasn't miraculous.

I can't help right now with Barrier Breaker. For ramips in BB, porting involves creating a DTS file, adding a build profile in image/Makefile and adding userland profiles in base-files. You can look at what's there for the AR725W and compare with what's here for AA. Might be a good project if you can hook up the serial console. If you do that, it's pretty tough to screw up because you can flash from the boot loader.

If you look at the commit history here you'll see the changes I had to make to support the WRT160Nv2. The mtd 'fix_uimage' thing in particular is tricky, but you can get around that by flashing from the bootloader or from OpenWrt-leitec.

**Comment by ShapeShifter499** [comment]
I'm probably ether going to store this in the closet or re-donate this router in favor of finding a new well supported router.  If you ever pick this project up again let me know.

**Comment by leitec** [comment]
I just saw the edit now, several months later, but I thought I'd answer anyway.

If I recall correctly, the model I used was a WRT110, not the 160Nv2. That one is very similar to the AR725W except with 16MB RAM, so it was just a quick edit of a few files. I didn't keep them, as far as I can tell, because it didn't work very well. The 160Nv2 would be trickier to support due to the aforementioned fix_uimage thing.

Given the similar hardware there's no reason to expect the 160v2 to behave any differently from the 110.
